name: flutter_whatsapp_notification
description: A Flutter application to send WhatsApp notifications using Twilio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  pdf: ^3.10.5
  path_provider: ^2.0.11
  googleapis: ^11.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
